export const LocalStorageKey = {
    AUTH_TOKEN: "AUTH_TOKEN",
    CLAIMS: "CLAIMS",
    LOGIN_DETAILS: "LOGIN_DETAILS",
    LESSONS: "LESSONS",
    COURSE: "COURSE",
    MODULES: "MODULES",
    CHAPTERS: "CHAPTERS",
    STUDENT_COURSE: "STUDENT_COURSE",
    PREVIOUS_URL: "PREVIOUS_URL"
  }