//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWDataTracker.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JWDataTracker.Infrastructure.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Publisher
        ///LIMIT 4,2;.
        /// </summary>
        internal static string PublisherGrid {
            get {
                return ResourceManager.GetString("PublisherGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(publisherid) as TotalCount from Publisher.
        /// </summary>
        internal static string PublisherGridCount {
            get {
                return ResourceManager.GetString("PublisherGridCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##ORDERBY##.
        /// </summary>
        internal static string QueryToken_OrderBy {
            get {
                return ResourceManager.GetString("QueryToken_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##SKIP##.
        /// </summary>
        internal static string QueryToken_Skip {
            get {
                return ResourceManager.GetString("QueryToken_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TAKE##.
        /// </summary>
        internal static string QueryToken_Take {
            get {
                return ResourceManager.GetString("QueryToken_Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##WHERE##.
        /// </summary>
        internal static string QueryToken_Where {
            get {
                return ResourceManager.GetString("QueryToken_Where", resourceCulture);
            }
        }
    }
}
